#!/bin/bash

CONFIG_SRC_DIR=~/Documents/configuration/src

if [ ! -d $CONFIG_SRC_DIR/.gitglobal ]; then
    git clone https://github.com/CaptainQuirk/.gitglobal.git $CONFIG_SRC_DIR/.gitglobal
    ln -s -f $CONFIG_SRC_DIR/.gitglobal/gitconfig ~/.gitconfig
    ln -s $CONFIG_SRC_DIR/.gitglobal/gitignore ~/.gitignore
fi

brew install git-flow
brew install tig

if [ ! -d $CONFIG_SRC_DIR/.tig ]; then
    git clone https://github.com/CaptainQuirk/.tig.git $CONFIG_SRC_DIR/.tig
    ln -s $CONFIG_SRC_DIR/.tig/tigrc ~/.tigrc
fi

sudo apt-get install git-flow

brew install git-extras
brew install git-cal

