#!/bin/bash

CONFIG_SRC_DIR=~/Documents/configuration/src
GIT_RECIPE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d $CONFIG_SRC_DIR/.gitglobal ]; then
    git clone https://github.com/CaptainQuirk/.gitglobal.git $CONFIG_SRC_DIR/.gitglobal
    ln -s -f $CONFIG_SRC_DIR/.gitglobal/gitconfig ~/.gitconfig
    ln -s $CONFIG_SRC_DIR/.gitglobal/gitignore ~/.gitignore
fi

cd $CONFIG_SRC_DIR/.gitglobal
git pull
cd -

if ! command -v tig >/dev/null 2>&1; then
    shef brew tig
else
    shef brew tig
fi

if [ ! -d $CONFIG_SRC_DIR/.tig ]; then
    git clone https://github.com/CaptainQuirk/.tig.git $CONFIG_SRC_DIR/.tig
    ln -s $CONFIG_SRC_DIR/.tig/tigrc ~/.tigrc
fi

cd $CONFIG_SRC_DIR/.tig
git pull
cd -

mkdir -p $HOME/Pictures/configuration
cp --update $GIT_RECIPE_DIR/files/git.png $HOME/.local/share/icons/

cp --update $GIT_RECIPE_DIR/files/tig.desktop $HOME/.local/share/applications/tig.desktop

sudo cp --update $GIT_RECIPE_DIR/files/tig-wrapper /usr/local/bin/tig-wrapper

if ! command -v git flow> /dev/null 2>&1; then
    sudo apt-get install git-flow
fi

shef brew git-extras
shef brew git-cal

if ! command -v git-open > /dev/null 2>&1; then
    npm install --global git-open
fi
