version: '3'
services:
    git-recipe:
      image: registry.gitlab.com/leonardmessier/shef/recipes/git-recipe:1.0.0
      build:
        context: ../
        dockerfile: .docker/Dockerfile
        args:
          - USERNAME=${USERNAME}
